apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: teamdagpenger
  name: dp-datadeling-cleanup
  namespace: teamdagpenger
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/teamdagpenger/curl:8.4.0
  schedule: "* * * * *"
  command:
    - -X POST http://dp-datadeling/internal/cleanup