apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-datadeling
  namespace: teamdagpenger
  labels:
    team: teamdagpenger

spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /isready
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: "{{ limitsMemory }}"
    requests:
      memory: "{{ requestsMemory }}"
      cpu: "{{ requestsCpu }}"
  ingresses:
  {{#each ingresses as |url|}}
      - {{ url }}
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        {{#each inbounds}}
        - application: "{{application}}"
          namespace: "{{namespace}}"
          cluster: "{{cluster}}"
          {{#if permissions}}
          permissions:
            roles:
              {{#each permissions.roles as |role|}}
              - {{ role }}
              {{/each}}
          {{/if}}
        {{/each}}
    outbound:
      rules:
        - application: dp-meldekortregister
        - application: logging
          namespace: nais-system
      external:
        - host: "{{ dpProxyHost }}"
  leaderElection: true
  env:
    - name: DP_MELDEKORTREGISTER_URL
      value: http://{{ dpMeldekortregisterHost }}
    - name: DP_MELDEKORTREGISTER_SCOPE
      value: "{{ dpMeldekortregisterScope }}"
    - name: DP_PROXY_URL
      value: https://{{ dpProxyHost }}
    - name: DP_PROXY_SCOPE
      value: "{{ dpProxyScope }}"
    - name: DP_DATADELING_URL
      value: https://{{ dpDatadelingHost }}

  azure:
    application:
      enabled: true
      allowAllUsers: true
  kafka:
    pool: "{{ kafka_pool }}"
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "afpprivat.read"
          enabled: true
          product: "dagpenger"
          consumers:
            - name: "Fellesordningen"
              orgno: "987414502"
  gcp:
    sqlInstances:
      - autoBackupHour: 5
        collation: nb_NO.UTF8
        databases:
          - envVarPrefix: DB
            name: datadeling
        diskAutoresize: true
        diskType: SSD
        flags:
          - name: "max_connections"
            value: "100"
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write,ddl,role"
          - name: "pgaudit.log_parameter"
            value: "on"
        highAvailability: true
        maintenance:
          day: 4
          hour: 3
        pointInTimeRecovery: false
        tier: "{{ db_tier }}"
        type: POSTGRES_15
        #cascadingDelete: true # DETTE ER EN DESTRUKTIV OPERASJON! cascadingDelete=true sletter db-instans hvis appen slettes
        # OBS! Man kan ikke opprette, slette og opprette instance igjen med en gang:
        # man kan ikke gjenbruke samme instansnavn på 7 dager. Dette er en "feature" i gcp.
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
