ktor:
  application:
    modules:
      - no.nav.dagpenger.datadeling.AppKt.module
  deployment:
    port: 8080

no.nav.security.jwt:
  issuer:
    azuread:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
      proxyurl: 'http://webproxy-nais.nav.no:8088'
      cookie_name: azure_token

DP_IVERKSETT_URL: "http://localhost:8094/api"