openapi: 3.0.0
info:
  title: Datadeling API
  version: 1.0.0

  description: |
    Tjenesten vil hente perioder personen har hatt dagpengerettighet av følgende varianter:
    * Ordinær dagpengerettighet for arbeidsledige
    * Dagpenger under permittering
    * Dagpenger under permittering fra fiskeindustrien
    
    Undervarianter av disse rettighetene vil også inkluderes:
    * Personer som har dagpenger på bakgrunn av vernepliktregelen (verneplikt tre av de siste tolv måneder)
    * Personer som har dagpenger på bakgrunn av lærlingeregelverket under koronapandemien
    
    Tjenesten vil ikke hente vedtak med informasjon om
    * Rett til forskutterte lønnsgarantimidler utbetalt som dagpenger
    * Rett til å ta med dagpengene til utlandet
    * Sanksjonsvedtak (forlenget ventetid eller tidsbegrenset bortfall – medfører at personen ikke får utbetaling i en periode)
    * Annullering av sanksjon
    
    Tjenesten vil hente perioder der personen har hatt vedtak om rett til dagpenger, selv om personen ikke har fått 
    utbetaling i hele/deler av perioden grunnet sanksjonsvedtak.
    
    Tjenesten vil hente perioder der personen har hatt vedtak om rett til dagpenger, selv om personen har hatt 
    enkeltdager eller meldeperioder uten rett til utbetaling, for eksempel grunnet arbeid over terskel for tapt 
    arbeidstid eller enkeltdager med fravær eller sykdom.
    
    Det er en utfordring med datakvaliteten, ved at endringer med tilbakevirkende kraft ikke reflekteres. Dataene som 
    utleveres tar ikke hensyn til eventuelle feilutbetalingssaker. Der en feilutbetalingssak har resultert i omgjøring 
    av vedtaksperioden, blir ikke dette reflektert i dataene som utleveres. Dette gjelder både for ferdig behandlede 
    feilutbetalingssaker og eventuelle etterfølgende feilutbetalingssaker. Vedtaksperiodene er dermed ikke nødvendigvis 
    korrekte. Det er imidlertid sjeldent at en feilutbetalingssak får betydning for vedtaksperiode, og det vil berøre 
    et lite antall saker.

servers:
  - url: https://dp-datadeling.ekstern.dev.nav.no
    description: dev

paths:
  /dagpenger/v1/periode:
    post:
      description: Mer beskrivelse
      summary: Oppsummering
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatadelingRequest'
      responses:
        201:
          description: Created
          content:
            text/plain:
              schema:
                type: string
                description: En url man kaller for å få svar på hvilke perioder en person har hatt retten til dagpenger
    get:
      parameters:
        - in: path
          name: ressursUuid
          required: true
          schema:
            type: string
            format: uuid
      description: Beskrivelse
      summary: Oppsummering
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ressurs'



components:
  schemas:
    # TODO: Bruke openapi genererte objekter. Objektene kommer fra dp-kontrakter, ikke autogenerert som vi burde

    DatadelingRequest:
      type: object
      required:
        - personIdent
        - fraOgMedDato
      properties:
        personIdent:
          type: string
          description: Personens fødselsnummer eller D-nummer
        fraOgMedDato:
          type: string
          format: date
          description: Tidligste dato man trenger informasjon om dagpengerettighet. Vedtak som er gyldige på denne dato vil bli med i responsen, selv om de starter tidligere. Vedtak som starter senere enn denne dato vil bli med i responsen hvis de ikke begrenses av tilOgMedDato (se beskrivelse under).
        tilOgMedDato:
          type: string
          format: date
          description: Seneste dato man trenger informasjon om dagpengerettighet. Vedtak som er gyldige på denne dato vil bli med i responsen, selv om de slutter senere. Vedtak med åpen til-dato vil bli med i responsen hvis de er gyldige på gitt tilOgMedDato.

    Ressurs:
      type: object
      required:
        - uuid
        - status
      properties:
        uuid:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/RessursStatus'
        response:
          $ref: '#/components/schemas/DatadelingResponse'

    RessursStatus:
      type: string
      enum:
        - OPPRETTET
        - FERDIG
        - FEILET

    DatadelingResponse:
      type: object
      required:
        - personIdent
        - perioder
      properties:
        personIdent:
          type: string
          description: Personens fødselsnummer eller D-nummer
        perioder:
          type: array
          description: Liste med perioder bruker har hatt retten til dagpenger. Kan være en tom liste.
          items:
            $ref: '#/components/schemas/Periode'

    Periode:
      type: object
      required:
        - fraOgMedDato
        - ytelseType
      properties:
        fraOgMedDato:
          type: string
          format: date
          description: Første dato ytelsen gjelder.
        tilOgMedDato:
          type: string
          format: date
          description: Siste dato ytelsen gjelder. Hvis elementet er tomt eller ikke er angitt, er ytelsen fortsatt aktiv.
        ytelseType:
          $ref: '#/components/schemas/YtelseType'


    YtelseType:
      type: string
      description: Type ytelse som gjelder i perioden.
      enum:
        - DAGPENGER_ARBEIDSSOKER_ORDINAER
        - DAGPENGER_PERMITTERING_ORDINAER
        - DAGPENGER_PERMITTERING_FISKEINDUSTRI
