name: Deploy cleanup job

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch hvor du vil deploye jobben"
        required: false
        type: string
        default: main

jobs:
  deployDev:
    name: Deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/cleanup-job.yaml
